##############################################
#        dnscrypt-proxy configuration        #
##############################################

server_names = [
  'yandex'
]

listen_addresses = ['127.0.0.1:863', '[::1]:863']

max_clients = 1024

##############################################
#        Фильтр серверов                     #
##############################################

ipv4_servers = true
ipv6_servers = false

dnscrypt_servers = true
doh_servers = true
odoh_servers = false

require_dnssec = false
require_nolog = false
require_nofilter = false

disabled_server_names = []

##############################################
#        Сеть / протоколы                    #
##############################################

force_tcp = true

http3 = false
http3_probe = false

#proxy = 'socks5://127.0.0.1:11990'

timeout = 7000
keepalive = 30

##############################################
#        Безопасность / нагрузка             #
##############################################

dnscrypt_ephemeral_keys = false

##############################################
#        Bootstrap DNS                       #
##############################################

bootstrap_resolvers = [
  '1.1.1.1:53',
  '9.9.9.9:53',
  '8.8.8.8:53',
  '77.88.8.8:53'
]

ignore_system_dns = true

netprobe_timeout = 120
netprobe_address = '1.1.1.1:53'

##############################################
#        Логи                                #
##############################################

log_file = '/data/adb/modules/ZDT-D/working_folder/dnscrypt/log/dnscrypt-proxy.log'

log_files_max_size = 1
log_files_max_age = 3
log_files_max_backups = 0

##############################################
#        Фильтрация                          #
##############################################

block_ipv6 = false
block_unqualified = true
block_undelegated = true
reject_ttl = 44

##############################################
#        DNS cache                           #
##############################################

cache = true
cache_size = 10000

cache_min_ttl = 600
cache_max_ttl = 3600

cache_neg_min_ttl = 60
cache_neg_max_ttl = 600

lb_estimator = true

##############################################
#        Cloaking / Forwarding               #
##############################################

cloaking_rules = 'cloaking-rules.txt'
cloak_ptr = false
forwarding_rules = 'forwarding-rules.txt'

##############################################
#        Blocklists TXT файлы                #
##############################################

[blocked_names]
blocked_names_file = 'blocked-names.txt'

[blocked_ips]
blocked_ips_file = 'blocked-ips.txt'

[allowed_names]
allowed_names_file = 'allowed-names.txt'

[allowed_ips]
allowed_ips_file = 'allowed-ips.txt'

##############################################
#        Captive portals                     #
##############################################

[captive_portals]
# map_file = 'captive-portals.txt'

##############################################
#        Отключён anonymized DNS             #
##############################################

[anonymized_dns]
routes = []

##############################################
#        Monitoring UI                       #
##############################################

[monitoring_ui]
enabled = false
listen_address = "127.0.0.1:8080"
username = "admin"
password = "changeme"

##############################################
#        Sources                             #
##############################################

[sources]

  [sources.'public-resolvers']
    urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/public-resolvers.md', 'https://download.dnscrypt.info/resolvers-list/v3/public-resolvers.md', 'https://cdn.jsdelivr.net/gh/DNSCrypt/dnscrypt-resolvers@master/v3/public-resolvers.md']
    minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
    cache_file = 'public-resolvers.md'

  [sources.'relays']
    urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/relays.md', 'https://download.dnscrypt.info/resolvers-list/v3/relays.md', 'https://cdn.jsdelivr.net/gh/DNSCrypt/dnscrypt-resolvers@master/v3/relays.md']
    minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
    cache_file = 'relays.md'

##############################################
#        Static custom DoH                   #
##############################################

[static]

# https://xbox-dns.ru/dns-query
[static.'xbox-dns-ru']
stamp = 'sdns://AgAAAAAAAAAAAAALeGJveC1kbnMucnUKL2Rucy1xdWVyeQ'

# https://ru-mow.doh.sb/dns-query
[static.'ru-mow-doh-sb']
stamp = 'sdns://AgAAAAAAAAAAAAANcnUtbW93LmRvaC5zYgovZG5zLXF1ZXJ5'

# https://router.comss.one/dns-query
[static.'router-comss-one']
stamp = 'sdns://AgAAAAAAAAAAAAAQcm91dGVyLmNvbXNzLm9uZQovZG5zLXF1ZXJ5'

# https://dns.malw.link/dns-query
[static.'dns.malw.link']
stamp = 'sdns://AgAAAAAAAAAADTgwLjI1My4yNDkuNDAADWRucy5tYWx3LmxpbmsKL2Rucy1xdWVyeQ'

# https://5u35p8m9i7.cloudflare-gateway.com/dns-query
[static.'dns.malw.link-cloudflare']
stamp = 'sdns://AgAAAAAAAAAAAAAhNXUzNXA4bTlpNy5jbG91ZGZsYXJlLWdhdGV3YXkuY29tCi9kbnMtcXVlcnk'

# https://free.shecan.ir/dns-query
[static.'free.shecan.ir']
stamp = 'sdns://AgAAAAAAAAAAAAAOZnJlZS5zaGVjYW4uaXIKL2Rucy1xdWVyeQ'

# https://dns.geohide.ru:444/dns-query
[static.'dns.geohide.ru']
stamp = 'sdns://AgAAAAAAAAAAAAASZG5zLmdlb2hpZGUucnU6NDQ0Ci9kbnMtcXVlcnk'

# https://doh.kel.pe
[static.'doh-kel-pe']
stamp = 'sdns://AgAAAAAAAAAAAAAKZG9oLmtlbC5wZQEv'

# https://dns.adnull.com/dns-query
[static.'dns-adnull']
stamp = 'sdns://AgAAAAAAAAAAAAAOZG5zLmFkbnVsbC5jb20KL2Rucy1xdWVyeQ'

# https://adfreedns.top/dns-query
[static.'adfreedns-top']
stamp = 'sdns://AgAAAAAAAAAAAAANYWRmcmVlZG5zLnRvcAovZG5zLXF1ZXJ5'